### ISSUE TITLE
possible bug - mysqli_connect() needs 4 parameters

### ISSUE THREAD

**Issue by Jimmi08** [eFiction/v3_stable#2]
in install/install.php you have , line 903:

`$mysql_access = mysqli_connect($dbhost, $dbuser, $dbpass);`

Maybe it should be this?
`$mysql_access = mysqli_connect($dbhost, $dbuser, $dbpass, $dbname);`

**Comment by campZero** [comment]
Yes and no.

In this specific case, mysqli_connect was used to simply check access for the credentials provided. So omitting the 4th parameter was valid use. One could add the $dbname parameter to cause a more precise check but this might happen at another point of the installer. (I am not the author of this, merely a watcher of legacy.)

The "no" part: I am not gonna implement this and validate it since this approacing EOL anyway.

**Comment by Jimmi08** [comment]
Thanks for the explanation.  It's ok then.
